// eslint disable below due to conflict between prettier and eslint within Trans components
// format below is the one generated by prettier
// be careful with changing line sturcture below: i18n translations reference specific nodes

/* eslint-disable react/jsx-one-expression-per-line */

import React from 'react';

import { Section, Container } from '@components/global';

import { useTranslation, Trans } from 'react-i18next';

import FaqItem from '@common/FaqItem';

import ASSOCIATION from '../../config/i18n/keys';
import {
  URL_GRAASP_SIGNUP,
  URL_GRAASP_ORG,
  MAILTO_CONTACT_GRAASP,
} from '../../config/hrefs';

const Faq = () => {
  const { t } = useTranslation();

  return (
    <Section id="faq">
      <Container>
        <h1 style={{ marginBottom: 40, color: '#211E26' }}>
          {t(ASSOCIATION.HEADER_FAQ)}
        </h1>
        <div>
          <FaqItem title={t(ASSOCIATION.QUESTION_PLATFORMS)}>
            <Trans
              components={[
                <a
                  href={URL_GRAASP_ORG}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Graasp
                </a>,
              ]}
            >
              {ASSOCIATION.ANSWER_PLATFORMS}
            </Trans>
          </FaqItem>
          <FaqItem title={t(ASSOCIATION.QUESTION_GRAASP)}>
            <Trans
              components={[
                <a
                  href={URL_GRAASP_ORG}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Graasp
                </a>,
              ]}
            >
              {ASSOCIATION.ANSWER_GRAASP}
            </Trans>
          </FaqItem>
          <FaqItem title={t(ASSOCIATION.QUESTION_GETTING_STARTED)}>
            <Trans
              components={[
                <a
                  href={URL_GRAASP_SIGNUP}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  here
                </a>,
              ]}
            >
              {ASSOCIATION.ANSWER_GETTING_STARTED}
            </Trans>
          </FaqItem>
          <FaqItem title={t(ASSOCIATION.QUESTION_COST)}>
            <Trans
              components={[
                <a
                  href={URL_GRAASP_ORG}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Graasp
                </a>,
                <a href={MAILTO_CONTACT_GRAASP}>contact@graasp.org</a>,
              ]}
            >
              {ASSOCIATION.ANSWER_COST}
            </Trans>
          </FaqItem>
          <FaqItem title={t(ASSOCIATION.QUESTION_TRAINING)}>
            <Trans
              components={[
                <a href={MAILTO_CONTACT_GRAASP}>contact@graasp.org</a>,
              ]}
            >
              {ASSOCIATION.ANSWER_TRAINING}
            </Trans>
          </FaqItem>
          <FaqItem title={t(ASSOCIATION.QUESTION_BASE)}>
            <Trans>{ASSOCIATION.ANSWER_BASE}</Trans>
          </FaqItem>
        </div>
      </Container>
    </Section>
  );
};

export default Faq;
